### ISSUE TITLE
Update API docs for source images

### ISSUE THREAD

**Issue by pstadler** [rokka-io/rokka-site#56]
Update example response for source images (see ["Retrieve data about a source image"](https://rokka.io/documentation/references/source-images.html )) to current format.

Maybe we should think about replacing the PHP examples with plain curl, as the number of rokka client libraries increases.

**Comment by chregu** [comment]
Ui, yeah, that was pretty wrong, fixed it

Yes, we need a better format for the different client libraries. Plain curl is usually already there, but the responses are missing.
